# Generated by Django 3.2.15 on 2022-08-18 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formSessions', '0002_enrolform_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolform',
            name='test',
        ),
    ]
