# Generated by Django 3.2.15 on 2022-08-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formSessions', '0003_remove_enrolform_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolform',
            name='address_state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
