# Generated by Django 3.2.15 on 2022-08-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formSessions', '0004_enrolform_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolform',
            name='address_2',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='enrolform',
            name='address_area',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='enrolform',
            name='address_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrolform',
            name='address_co',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrolform',
            name='address_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrolform',
            name='address_landmark',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='enrolform',
            name='address_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrolform',
            name='address_postoffice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrolform',
            name='address_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrolform',
            name='address_subdistrict',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
