# Generated by Django 3.2.15 on 2022-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formSessions', '0005_auto_20220825_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolform',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
