# Generated by Django 3.2.15 on 2022-08-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formSessions', '0006_alter_enrolform_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolform',
            name='lastname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolform',
            name='middlename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
